// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: api/proto/cache.proto

package KydDB

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cache entry representation
type CacheEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Key              string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value            []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	LastModifiedTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_modified_time,json=lastModifiedTime,proto3" json:"last_modified_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CacheEntry) Reset() {
	*x = CacheEntry{}
	mi := &file_api_proto_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheEntry) ProtoMessage() {}

func (x *CacheEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheEntry.ProtoReflect.Descriptor instead.
func (*CacheEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{0}
}

func (x *CacheEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CacheEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CacheEntry) GetLastModifiedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedTime
	}
	return nil
}

// Node information
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_api_proto_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

// Cluster management messages
type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeInfo      *NodeInfo              `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRequest) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_api_proto_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{3}
}

func (x *JoinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type LeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveResponse) Reset() {
	*x = LeaveResponse{}
	mi := &file_api_proto_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse) ProtoMessage() {}

func (x *LeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse.ProtoReflect.Descriptor instead.
func (*LeaveResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{5}
}

func (x *LeaveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{6}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesRequest) Reset() {
	*x = GetNodesRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesRequest) ProtoMessage() {}

func (x *GetNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesRequest.ProtoReflect.Descriptor instead.
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{8}
}

type GetNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesResponse) Reset() {
	*x = GetNodesResponse{}
	mi := &file_api_proto_cache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesResponse) ProtoMessage() {}

func (x *GetNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesResponse.ProtoReflect.Descriptor instead.
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{9}
}

func (x *GetNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// Cache operation messages
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{10}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_proto_cache_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{11}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{12}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_api_proto_cache_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{13}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RebalanceAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*CacheEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebalanceAddRequest) Reset() {
	*x = RebalanceAddRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceAddRequest) ProtoMessage() {}

func (x *RebalanceAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceAddRequest.ProtoReflect.Descriptor instead.
func (*RebalanceAddRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{14}
}

func (x *RebalanceAddRequest) GetEntries() []*CacheEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RebalanceAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebalanceAddResponse) Reset() {
	*x = RebalanceAddResponse{}
	mi := &file_api_proto_cache_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceAddResponse) ProtoMessage() {}

func (x *RebalanceAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceAddResponse.ProtoReflect.Descriptor instead.
func (*RebalanceAddResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{15}
}

func (x *RebalanceAddResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RebalanceAddResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RebalanceRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebalanceRemoveRequest) Reset() {
	*x = RebalanceRemoveRequest{}
	mi := &file_api_proto_cache_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceRemoveRequest) ProtoMessage() {}

func (x *RebalanceRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceRemoveRequest.ProtoReflect.Descriptor instead.
func (*RebalanceRemoveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{16}
}

func (x *RebalanceRemoveRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type RebalanceRemoveResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RemovedEntries []*CacheEntry          `protobuf:"bytes,1,rep,name=removed_entries,json=removedEntries,proto3" json:"removed_entries,omitempty"`
	Error          string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RebalanceRemoveResponse) Reset() {
	*x = RebalanceRemoveResponse{}
	mi := &file_api_proto_cache_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceRemoveResponse) ProtoMessage() {}

func (x *RebalanceRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cache_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceRemoveResponse.ProtoReflect.Descriptor instead.
func (*RebalanceRemoveResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cache_proto_rawDescGZIP(), []int{17}
}

func (x *RebalanceRemoveResponse) GetRemovedEntries() []*CacheEntry {
	if x != nil {
		return x.RemovedEntries
	}
	return nil
}

func (x *RebalanceRemoveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_cache_proto protoreflect.FileDescriptor

const file_api_proto_cache_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/cache.proto\x12\x05kyddb\x1a\x1fgoogle/protobuf/timestamp.proto\"~\n" +
	"\n" +
	"CacheEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12H\n" +
	"\x12last_modified_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x10lastModifiedTime\"\x81\x01\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x127\n" +
	"\tlast_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\";\n" +
	"\vJoinRequest\x12,\n" +
	"\tnode_info\x18\x01 \x01(\v2\x0f.kyddb.NodeInfoR\bnodeInfo\"(\n" +
	"\fJoinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\fLeaveRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\")\n" +
	"\rLeaveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12HealthCheckRequest\"\x80\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x11\n" +
	"\x0fGetNodesRequest\"9\n" +
	"\x10GetNodesResponse\x12%\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0f.kyddb.NodeInfoR\x05nodes\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"O\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"4\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"=\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"B\n" +
	"\x13RebalanceAddRequest\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.kyddb.CacheEntryR\aentries\"F\n" +
	"\x14RebalanceAddResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\",\n" +
	"\x16RebalanceRemoveRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"k\n" +
	"\x17RebalanceRemoveResponse\x12:\n" +
	"\x0fremoved_entries\x18\x01 \x03(\v2\x11.kyddb.CacheEntryR\x0eremovedEntries\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xec\x03\n" +
	"\vNodeService\x12/\n" +
	"\x04Join\x12\x12.kyddb.JoinRequest\x1a\x13.kyddb.JoinResponse\x122\n" +
	"\x05Leave\x12\x13.kyddb.LeaveRequest\x1a\x14.kyddb.LeaveResponse\x12D\n" +
	"\vHealthCheck\x12\x19.kyddb.HealthCheckRequest\x1a\x1a.kyddb.HealthCheckResponse\x12;\n" +
	"\bGetNodes\x12\x16.kyddb.GetNodesRequest\x1a\x17.kyddb.GetNodesResponse\x12,\n" +
	"\x03Get\x12\x11.kyddb.GetRequest\x1a\x12.kyddb.GetResponse\x12,\n" +
	"\x03Set\x12\x11.kyddb.SetRequest\x1a\x12.kyddb.SetResponse\x12G\n" +
	"\fRebalanceAdd\x12\x1a.kyddb.RebalanceAddRequest\x1a\x1b.kyddb.RebalanceAddResponse\x12P\n" +
	"\x0fRebalanceRemove\x12\x1d.kyddb.RebalanceRemoveRequest\x1a\x1e.kyddb.RebalanceRemoveResponseB!Z\x1fgithub.com/Waelthecreator/KydDBb\x06proto3"

var (
	file_api_proto_cache_proto_rawDescOnce sync.Once
	file_api_proto_cache_proto_rawDescData []byte
)

func file_api_proto_cache_proto_rawDescGZIP() []byte {
	file_api_proto_cache_proto_rawDescOnce.Do(func() {
		file_api_proto_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cache_proto_rawDesc), len(file_api_proto_cache_proto_rawDesc)))
	})
	return file_api_proto_cache_proto_rawDescData
}

var file_api_proto_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_cache_proto_goTypes = []any{
	(*CacheEntry)(nil),              // 0: kyddb.CacheEntry
	(*NodeInfo)(nil),                // 1: kyddb.NodeInfo
	(*JoinRequest)(nil),             // 2: kyddb.JoinRequest
	(*JoinResponse)(nil),            // 3: kyddb.JoinResponse
	(*LeaveRequest)(nil),            // 4: kyddb.LeaveRequest
	(*LeaveResponse)(nil),           // 5: kyddb.LeaveResponse
	(*HealthCheckRequest)(nil),      // 6: kyddb.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 7: kyddb.HealthCheckResponse
	(*GetNodesRequest)(nil),         // 8: kyddb.GetNodesRequest
	(*GetNodesResponse)(nil),        // 9: kyddb.GetNodesResponse
	(*GetRequest)(nil),              // 10: kyddb.GetRequest
	(*GetResponse)(nil),             // 11: kyddb.GetResponse
	(*SetRequest)(nil),              // 12: kyddb.SetRequest
	(*SetResponse)(nil),             // 13: kyddb.SetResponse
	(*RebalanceAddRequest)(nil),     // 14: kyddb.RebalanceAddRequest
	(*RebalanceAddResponse)(nil),    // 15: kyddb.RebalanceAddResponse
	(*RebalanceRemoveRequest)(nil),  // 16: kyddb.RebalanceRemoveRequest
	(*RebalanceRemoveResponse)(nil), // 17: kyddb.RebalanceRemoveResponse
	(*timestamppb.Timestamp)(nil),   // 18: google.protobuf.Timestamp
}
var file_api_proto_cache_proto_depIdxs = []int32{
	18, // 0: kyddb.CacheEntry.last_modified_time:type_name -> google.protobuf.Timestamp
	18, // 1: kyddb.NodeInfo.last_seen:type_name -> google.protobuf.Timestamp
	1,  // 2: kyddb.JoinRequest.node_info:type_name -> kyddb.NodeInfo
	18, // 3: kyddb.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 4: kyddb.GetNodesResponse.nodes:type_name -> kyddb.NodeInfo
	0,  // 5: kyddb.RebalanceAddRequest.entries:type_name -> kyddb.CacheEntry
	0,  // 6: kyddb.RebalanceRemoveResponse.removed_entries:type_name -> kyddb.CacheEntry
	2,  // 7: kyddb.NodeService.Join:input_type -> kyddb.JoinRequest
	4,  // 8: kyddb.NodeService.Leave:input_type -> kyddb.LeaveRequest
	6,  // 9: kyddb.NodeService.HealthCheck:input_type -> kyddb.HealthCheckRequest
	8,  // 10: kyddb.NodeService.GetNodes:input_type -> kyddb.GetNodesRequest
	10, // 11: kyddb.NodeService.Get:input_type -> kyddb.GetRequest
	12, // 12: kyddb.NodeService.Set:input_type -> kyddb.SetRequest
	14, // 13: kyddb.NodeService.RebalanceAdd:input_type -> kyddb.RebalanceAddRequest
	16, // 14: kyddb.NodeService.RebalanceRemove:input_type -> kyddb.RebalanceRemoveRequest
	3,  // 15: kyddb.NodeService.Join:output_type -> kyddb.JoinResponse
	5,  // 16: kyddb.NodeService.Leave:output_type -> kyddb.LeaveResponse
	7,  // 17: kyddb.NodeService.HealthCheck:output_type -> kyddb.HealthCheckResponse
	9,  // 18: kyddb.NodeService.GetNodes:output_type -> kyddb.GetNodesResponse
	11, // 19: kyddb.NodeService.Get:output_type -> kyddb.GetResponse
	13, // 20: kyddb.NodeService.Set:output_type -> kyddb.SetResponse
	15, // 21: kyddb.NodeService.RebalanceAdd:output_type -> kyddb.RebalanceAddResponse
	17, // 22: kyddb.NodeService.RebalanceRemove:output_type -> kyddb.RebalanceRemoveResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_cache_proto_init() }
func file_api_proto_cache_proto_init() {
	if File_api_proto_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cache_proto_rawDesc), len(file_api_proto_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cache_proto_goTypes,
		DependencyIndexes: file_api_proto_cache_proto_depIdxs,
		MessageInfos:      file_api_proto_cache_proto_msgTypes,
	}.Build()
	File_api_proto_cache_proto = out.File
	file_api_proto_cache_proto_goTypes = nil
	file_api_proto_cache_proto_depIdxs = nil
}
